name: CI

on:
  push:
    branches:
      - master
      - 'v*' # older version branches
    tags:
      - '*'
  pull_request: {}

jobs:
  test:
    timeout-minutes: 5
    name: Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: ['16', '18', '20']
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
        with:
          node-version: ${{ matrix.node }}
      - name: yarn --frozen-lockfile
        run: YARN_IGNORE_NODE=1 yarn --frozen-lockfile
      - run: YARN_IGNORE_NODE=1 yarn build
      - run: YARN_IGNORE_NODE=1 yarn test
      - run: YARN_IGNORE_NODE=1 yarn test:browser
